// Generated by API code generator

import { SignupRequest, SignupResponse, SignInRequest, SignInResponse, GetUserResponse, GetUsersQuery, GetUsersResponse, UpdateUserRequest, UpdateUserResponse, SignOutResponse, GetUserParams, UpdateUserParams } from './types';

export interface RequestOptions {
  headers?: Record<string, string>;
  timeout?: number;
}

export class GonzoServerClient {
  constructor(private baseUrl: string) {}

	// Authentication endpoints
  async signup(body: SignupRequest, options?: RequestOptions): Promise<SignupResponse> {
    let url = `${this.baseUrl}/auth/signup`;
    
    
    const response = await fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers
      },
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
  async signIn(body: SignInRequest, options?: RequestOptions): Promise<SignInResponse> {
    let url = `${this.baseUrl}/auth/signin`;
    
    
    const response = await fetch(url, {
      method: 'POST',
      body: JSON.stringify(body),
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers
      },
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
  async signOut(options?: RequestOptions): Promise<SignOutResponse> {
    let url = `${this.baseUrl}/auth/signout`;
    
    
    const response = await fetch(url, {
      method: 'POST',
      headers: options?.headers,
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
	// User management endpoints (require authentication)
  async getUser(params: GetUserParams, options?: RequestOptions): Promise<GetUserResponse> {
    let url = `${this.baseUrl}/user/{UserID}`;
    
    // Replace path parameters
    url = url.replace('{UserID}', String(params.UserID));
    
    const response = await fetch(url, {
      method: 'GET',
      headers: options?.headers,
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
  async getUsers(parameters: GetUsersQuery, options?: RequestOptions): Promise<GetUsersResponse> {
    let url = `${this.baseUrl}/users`;
    
    
    // Add query parameters
    const searchParams = new URLSearchParams();
    Object.entries(parameters).forEach(([key, value]) => {
      if (value !== undefined) {
        searchParams.append(key, String(value));
      }
    });
    if (searchParams.toString()) {
      url += '?' + searchParams.toString();
    }
    
    const response = await fetch(url, {
      method: 'GET',
      headers: options?.headers,
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
  async updateUser(body: UpdateUserRequest, params: UpdateUserParams, options?: RequestOptions): Promise<UpdateUserResponse> {
    let url = `${this.baseUrl}/user/{UserID}`;
    
    // Replace path parameters
    url = url.replace('{UserID}', String(params.UserID));
    
    const response = await fetch(url, {
      method: 'PUT',
      body: JSON.stringify(body),
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers
      },
      signal: options?.timeout ? AbortSignal.timeout(options.timeout) : undefined
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    return response.json();
  }
}
