// Generated by API code generator


export enum UserRole {
  ADMIN = "admin",
  USER = "user",
}



// User authentication and management API
export type UserID = number;


export interface User {
  ID: UserID;
  Username: string;
  Email: string;
  Role?: UserRole;
  CreatedAt?: number;
}


export interface Session {
  UserID: UserID;
  Token: string;
  ExpiresAt?: number;
}


export interface SignupRequest {
  Username: string;
  Email: string;
  Password: string;
}


export interface SignupResponse {
  User: User;
  Session: Session;
}


export interface SignInRequest {
  Email: string;
  Password: string;
}


export interface SignInResponse {
  User: User;
  Session: Session;
}


export interface GetUserResponse {
  User: User;
}


export interface GetUsersQuery {
  Limit?: number;
  Offset?: number;
  Role?: UserRole;
}


export interface GetUsersResponse {
  Users: Array<User>;
  Total?: number;
}


export interface UpdateUserRequest {
  Username?: string;
  Email?: string;
  Role?: UserRole;
}


export interface UpdateUserResponse {
  User: User;
}


export interface SignOutResponse {
  Success: boolean;
}


// Error response type
export interface ErrorResponse {
  Error: string;
  Code: string;
}



export interface GetUserParams {
  UserID: UserID;
}
export interface UpdateUserParams {
  UserID: UserID;
}

