// Generated by API code generator


export type UserRole = "admin" | "user";



// User authentication and management API
export type UserID = number;


export interface User {
  id: UserID;
  username: string;
  email: string;
  role?: UserRole;
  createdAt?: number;
}


export interface Session {
  userId: UserID;
  token: string;
  expiresAt?: number;
}


export interface SignupRequest {
  username: string;
  email: string;
  password: string;
}


export interface SignupResponse {
  user: User;
  session: Session;
}


export interface SignInRequest {
  email: string;
  password: string;
}


export interface SignInResponse {
  user: User;
  session: Session;
}


export interface GetUserResponse {
  user: User;
}


export interface GetUsersQuery {
  limit?: number;
  offset?: number;
  role?: UserRole;
}


export interface GetUsersResponse {
  users: Array<User>;
  total?: number;
}


export interface UpdateUserRequest {
  username?: string;
  email?: string;
  role?: UserRole;
}


export interface UpdateUserResponse {
  user: User;
}


export interface SignOutResponse {
  success: boolean;
}


// Error response type
export interface ErrorResponse {
  error: string;
  code: string;
}



export interface GetUserParams {
  UserID: UserID;
}
export interface UpdateUserParams {
  UserID: UserID;
}

