package output

import (
	"fmt"
	"strings"

	"github.com/medubin/gonzo/api/generate/data"
)

func Types(d *data.Data) string {
	header := outputHeader()
	variables := outputVariables(d.Variables)
	server := outputServers(d.Servers)
	serverStart := outputServerStarts(d.Servers)

	return strings.Join([]string{
		header, variables, server, serverStart,
	}, "\n\n")
}

func outputHeader() string {
	return `// Code generated by Gonzo DO NOT EDIT.
	package server
	import (
		"context"

		"github.com/medubin/gonzo/api/src/cookies"
		"github.com/medubin/gonzo/api/src/handle"
		"github.com/medubin/gonzo/api/src/router"
		"github.com/medubin/gonzo/api/src/url"
	)
	`
}

func outputVariables(vs []data.Variable) string {
	output := ""
	for _, v := range vs {
		output += outputVariable(v)
	}
	return output
}

func outputServers(ss []data.Server) string {
	output := ""
	for _, s := range ss {
		output += outputServer(s)
	}
	return output
}

func outputServerStarts(ss []data.Server) string {
	output := ""
	for _, s := range ss {
		output += outputServerStart(s)
	}
	return output
}

func outputVariable(v data.Variable) string {
	variableOutput := ""
	functionOutput := ""
	isStruct := v.Type == "{"

	vType := v.Type
	if isStruct {
		vType = "struct {"
	} else {
		vType = "*" + vType
	}

	variableOutput += fmt.Sprintf("type %s %s\n", v.Name, vType)

	for _, field := range v.Fields {
		variableOutput += fmt.Sprintf("%s *%s\n", field.Name, field.Type)
		functionOutput += fmt.Sprintf("func (s *%s) Get%s() *%s {\n ", v.Name, field.Name, field.Type)
		functionOutput += "if (s == nil) {\n return nil\n}\n"
		functionOutput += fmt.Sprintf("return s.%s\n}\n\n", field.Name)
	}
	if isStruct {
		variableOutput += "}\n"
	}
	return variableOutput + "\n\n" + functionOutput

}

func outputServer(s data.Server) string {
	server := "type Server interface {\n"

	endpointList := []string{}
	for _, e := range s.Endpoints {
		endpointList = append(endpointList, generateEndpoint(e))
	}

	server += strings.Join(endpointList, "\n")
	return server + "}"
}

func outputServerStart(server data.Server) string {
	serverInit := "func StartServer(s Server, r *router.Router) {"
	for _, e := range server.Endpoints {
		serverInit += fmt.Sprintf("r.Route(\"%s\", \"%s\", handle.Handle(s.%s))\n", e.Verb, e.Url, e.Name)
	}

	return serverInit + "}\n\n"
}
