// Generated by API code generator

export type ErrorCode =
  | 'invalid_argument'
  | 'missing_argument'
  | 'not_found'
  | 'already_exists'
  | 'unauthenticated'
  | 'unimplemented'
  | 'internal'
  | 'bad_route'
  | 'malformed';

export class GonzoError extends Error {
  readonly code: ErrorCode;
  readonly statusCode: number;

  constructor(code: ErrorCode, message: string, statusCode: number) {
    super(message);
    this.name = 'GonzoError';
    this.code = code;
    this.statusCode = statusCode;
  }
}

export class InvalidArgumentError extends GonzoError {
  constructor(message: string, statusCode = 400) {
    super('invalid_argument', message, statusCode);
    this.name = 'InvalidArgumentError';
  }
}

export class MissingArgumentError extends GonzoError {
  constructor(message: string, statusCode = 400) {
    super('missing_argument', message, statusCode);
    this.name = 'MissingArgumentError';
  }
}

export class NotFoundError extends GonzoError {
  constructor(message: string, statusCode = 404) {
    super('not_found', message, statusCode);
    this.name = 'NotFoundError';
  }
}

export class AlreadyExistsError extends GonzoError {
  constructor(message: string, statusCode = 409) {
    super('already_exists', message, statusCode);
    this.name = 'AlreadyExistsError';
  }
}

export class UnauthenticatedError extends GonzoError {
  constructor(message: string, statusCode = 401) {
    super('unauthenticated', message, statusCode);
    this.name = 'UnauthenticatedError';
  }
}

export class UnimplementedError extends GonzoError {
  constructor(message: string, statusCode = 501) {
    super('unimplemented', message, statusCode);
    this.name = 'UnimplementedError';
  }
}

export class InternalError extends GonzoError {
  constructor(message: string, statusCode = 500) {
    super('internal', message, statusCode);
    this.name = 'InternalError';
  }
}

export class BadRouteError extends GonzoError {
  constructor(message: string, statusCode = 404) {
    super('bad_route', message, statusCode);
    this.name = 'BadRouteError';
  }
}

export class MalformedError extends GonzoError {
  constructor(message: string, statusCode = 400) {
    super('malformed', message, statusCode);
    this.name = 'MalformedError';
  }
}

export async function parseGonzoError(response: Response): Promise<GonzoError> {
  const statusCode = response.status;
  let code: ErrorCode = 'internal';
  let message = response.statusText || 'unknown error';

  try {
    const body = await response.json();
    if (body.error && typeof body.error === 'string') {
      const colonIdx = body.error.indexOf(': ');
      if (colonIdx !== -1) {
        code = body.error.substring(0, colonIdx) as ErrorCode;
        message = body.error.substring(colonIdx + 2);
      } else {
        message = body.error;
      }
    }
  } catch (_) {}

  switch (code) {
    case 'invalid_argument': return new InvalidArgumentError(message, statusCode);
    case 'missing_argument': return new MissingArgumentError(message, statusCode);
    case 'not_found': return new NotFoundError(message, statusCode);
    case 'already_exists': return new AlreadyExistsError(message, statusCode);
    case 'unauthenticated': return new UnauthenticatedError(message, statusCode);
    case 'unimplemented': return new UnimplementedError(message, statusCode);
    case 'internal': return new InternalError(message, statusCode);
    case 'bad_route': return new BadRouteError(message, statusCode);
    case 'malformed': return new MalformedError(message, statusCode);
    default: return new GonzoError('internal', message, statusCode);
  }
}
