// Package generated by API code generator
package server

import (
	"context"
	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/middleware"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/url"
)


/*
 * Servers contain endpoints.
 * Each endpoint is defined as a name, verb url, optional body and optional returns
 */
type UserService interface {
	// Endpoints can contain url parameters, which can be any primitive type or enum
	// GET endpoints do not contain a body
	GetUser(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[struct{}, GetUserUrl]) (*DetailedUser, error)
	// All other urls can contain a body
	// body and return always refer to a struct type
	CreateUser(ctx context.Context, body *CreateUserRequest, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*User, error)
	UpdateUser(ctx context.Context, body *UpdateUserRequest, cookie cookies.Cookies, url url.URL[struct{}, UpdateUserUrl]) (*User, error)
	DeleteUser(ctx context.Context, body *DeleteUserRequest, cookie cookies.Cookies, url url.URL[struct{}, DeleteUserUrl]) (*User, error)
	PatchUserProfile(ctx context.Context, body *UserProfileUpdate, cookie cookies.Cookies, url url.URL[struct{}, PatchUserProfileUrl]) (*UserProfile, error)
	// Endpoints can take a struct of parameters
	ListUsers(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, struct{}]) (*UserCollection, error)
	SearchUsers(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserSearchParams, struct{}]) (*UserCollection, error)
	GetUsersByRole(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, GetUsersByRoleUrl]) (*UserCollection, error)
}

func StartUserService(s UserService, r *router.Router) {
	r.RouteWithInfo("GET", "/users/{id}", handle.Handle(s.GetUser), &middleware.RouteInfo{
  Method: "GET",
  Path: "/users/{id}",
  Endpoint: "GetUser",
  Server: "UserService",
  RequiresBody: false,
  })
	r.RouteWithInfo("POST", "/users", handle.Handle(s.CreateUser), &middleware.RouteInfo{
  Method: "POST",
  Path: "/users",
  Endpoint: "CreateUser",
  Server: "UserService",
  RequiresBody: true,
  })
	r.RouteWithInfo("PUT", "/users/{id}", handle.Handle(s.UpdateUser), &middleware.RouteInfo{
  Method: "PUT",
  Path: "/users/{id}",
  Endpoint: "UpdateUser",
  Server: "UserService",
  RequiresBody: true,
  })
	r.RouteWithInfo("DELETE", "/users/{id}", handle.Handle(s.DeleteUser), &middleware.RouteInfo{
  Method: "DELETE",
  Path: "/users/{id}",
  Endpoint: "DeleteUser",
  Server: "UserService",
  RequiresBody: false,
  })
	r.RouteWithInfo("PATCH", "/users/{id}/profile", handle.Handle(s.PatchUserProfile), &middleware.RouteInfo{
  Method: "PATCH",
  Path: "/users/{id}/profile",
  Endpoint: "PatchUserProfile",
  Server: "UserService",
  RequiresBody: true,
  })
	r.RouteWithInfo("GET", "/users", handle.Handle(s.ListUsers), &middleware.RouteInfo{
  Method: "GET",
  Path: "/users",
  Endpoint: "ListUsers",
  Server: "UserService",
  RequiresBody: false,
  })
	r.RouteWithInfo("GET", "/users/search", handle.Handle(s.SearchUsers), &middleware.RouteInfo{
  Method: "GET",
  Path: "/users/search",
  Endpoint: "SearchUsers",
  Server: "UserService",
  RequiresBody: false,
  })
	r.RouteWithInfo("GET", "/users/role/{role}", handle.Handle(s.GetUsersByRole), &middleware.RouteInfo{
  Method: "GET",
  Path: "/users/role/{role}",
  Endpoint: "GetUsersByRole",
  Server: "UserService",
  RequiresBody: false,
  })
}

// multiple servers can be defined in a single file
type NotificationService interface {
	GetUserNotifications(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, GetUserNotificationsUrl]) (*[]Notification, error)
}

func StartNotificationService(s NotificationService, r *router.Router) {
	r.RouteWithInfo("GET", "/users/{userId}/notifications", handle.Handle(s.GetUserNotifications), &middleware.RouteInfo{
  Method: "GET",
  Path: "/users/{userId}/notifications",
  Endpoint: "GetUserNotifications",
  Server: "NotificationService",
  RequiresBody: false,
  })
}

