// Package generated by API code generator
package server

import (
	"context"
	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/url"
)


/*
 * Servers contain endpoints.
 * Each endpoint is defined as a name, verb url, optional body and optional returns
 */
type UserService interface {
	// Endpoints can contain url parameters, which can be any primitive type or enum
	// GET endpoints do not contain a body
	GetUser(ctx context.Context, body *any, cookie cookies.Cookies, url url.URL[GetUserUrl]) (*DetailedUser, error)
	// All other urls can contain a body
	// body and return always refer to a struct type
	CreateUser(ctx context.Context, body *CreateUserRequest, cookie cookies.Cookies, url url.URL[any]) (*User, error)
	UpdateUser(ctx context.Context, body *UpdateUserRequest, cookie cookies.Cookies, url url.URL[UpdateUserUrl]) (*User, error)
	DeleteUser(ctx context.Context, body *DeleteUserRequest, cookie cookies.Cookies, url url.URL[DeleteUserUrl]) (*User, error)
	PatchUserProfile(ctx context.Context, body *UserProfileUpdate, cookie cookies.Cookies, url url.URL[PatchUserProfileUrl]) (*UserProfile, error)
	// Endpoints can take a struct of parameters
	ListUsers(ctx context.Context, body *any, cookie cookies.Cookies, url url.URL[any]) (*UserCollection, error)
	SearchUsers(ctx context.Context, body *any, cookie cookies.Cookies, url url.URL[any]) (*UserCollection, error)
	GetUsersByRole(ctx context.Context, body *any, cookie cookies.Cookies, url url.URL[GetUsersByRoleUrl]) (*UserCollection, error)
}

func StartUserService(s UserService, r *router.Router) {
	r.Route("GET", "/users/{id}", handle.Handle(s.GetUser))
	r.Route("POST", "/users", handle.Handle(s.CreateUser))
	r.Route("PUT", "/users/{id}", handle.Handle(s.UpdateUser))
	r.Route("DELETE", "/users/{id}", handle.Handle(s.DeleteUser))
	r.Route("PATCH", "/users/{id}/profile", handle.Handle(s.PatchUserProfile))
	r.Route("GET", "/users", handle.Handle(s.ListUsers))
	r.Route("GET", "/users/search", handle.Handle(s.SearchUsers))
	r.Route("GET", "/users/role/{role}", handle.Handle(s.GetUsersByRole))
}

// multiple servers can be defined in a single file
type NotificationService interface {
	GetUserNotifications(ctx context.Context, body *any, cookie cookies.Cookies, url url.URL[GetUserNotificationsUrl]) (*[]Notification, error)
}

func StartNotificationService(s NotificationService, r *router.Router) {
	r.Route("GET", "/users/{userId}/notifications", handle.Handle(s.GetUserNotifications))
}

