// Package generated by API code generator
package test


// enums can be defined like this
// enums can be any primitive type
type UserRole string

const (
	UserRole_USER UserRole = "user"
	UserRole_ADMIN UserRole = "admin"
	UserRole_MODERATOR UserRole = "moderator"
)

type UserStatus string

const (
	UserStatus_PENDING UserStatus = "pending"
	UserStatus_ACTIVE UserStatus = "active"
	UserStatus_SUSPENDED UserStatus = "suspended"
)

type WelcomeMessage string

const (
	WelcomeMessage_WELCOME WelcomeMessage = "Welcome to "MyApp""
)



// this is a comment
/* this is a multiline comment */
// you can define primitives like this
type UserID int64


// this is also a comment
type Email string


type Timestamp int64


type Score float32


type IsActive bool


// you can defined lists this way
type UserList []User


// you can use types before they are defined
type NotificationID int32


// lists can be complex
type UserRoleHistory [][]string


type NestedUserGroups [][]UserList


// you can defined maps this way
type UserPermissions map[string]bool


// maps can be complex
type UserActivityByMonth map[string]map[int64][]int32


// structs can be defined like this
type User struct {
	ID UserID `json:"id,omitempty"`
	Username string `json:"username,omitempty"`
	Email Email `json:"email,omitempty"`
	Role UserRole `json:"role,omitempty"`
}


/*
 * Struct fields can contain:
 * ** any primitives
 * ** repeated fields
 * ** map fields
 * ** any defined types
 * ** other structs
 */
type DetailedUser struct {
	// fields are optional unless marked with 'required'
	ID UserID `json:"id"`
	Usernames []string `json:"usernames,omitempty"`
	LoginCount map[string]int32 `json:"logincount,omitempty"`
	Profile UserProfile `json:"profile,omitempty"`
}


type UserProfile struct {
	FirstName string `json:"firstname,omitempty"`
	LastName string `json:"lastname,omitempty"`
	Bio string `json:"bio,omitempty"`
	AvatarUrl string `json:"avatarurl,omitempty"`
}


// both lists and maps can contain structs
type UserCollection []User


type UsersByDepartment map[string]User


/*
 * Allowed in parameter structs:
 * - Primitives: string, int32, int64, float32, float64, bool
 * - Enums (serialize to underlying primitive)
 * - Simple arrays: repeated(primitive) or repeated(enum)
 * - Maybe simple maps: map(string: primitive)
 */
type UserSearchParams struct {
	Query string `json:"query,omitempty"`
	Roles []UserRole `json:"roles,omitempty"`
	IsActive bool `json:"isactive,omitempty"`
	Limit int32 `json:"limit,omitempty"`
}


type UserListParams struct {
	Page int32 `json:"page,omitempty"`
	PageSize int32 `json:"pagesize,omitempty"`
	SortBy string `json:"sortby,omitempty"`
	SortOrder string `json:"sortorder,omitempty"`
}


type CreateUserRequest struct {
	Username string `json:"username"`
	Email Email `json:"email"`
	Password string `json:"password"`
	Role UserRole `json:"role,omitempty"`
	Profile UserProfile `json:"profile,omitempty"`
}


type UpdateUserRequest struct {
	Username string `json:"username,omitempty"`
	Email Email `json:"email,omitempty"`
	Role UserRole `json:"role,omitempty"`
	Status UserStatus `json:"status,omitempty"`
}


type DeleteUserRequest struct {
	Reason string `json:"reason,omitempty"`
	TransferDataTo UserID `json:"transferdatato,omitempty"`
}


type UserProfileUpdate struct {
	FirstName string `json:"firstname,omitempty"`
	LastName string `json:"lastname,omitempty"`
	Bio string `json:"bio,omitempty"`
	AvatarUrl string `json:"avatarurl,omitempty"`
}


type Notification struct {
	ID NotificationID `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
	Message string `json:"message,omitempty"`
	CreatedAt Timestamp `json:"createdat,omitempty"`
	IsRead bool `json:"isread,omitempty"`
}



// URL parameters for GetUser
type GetUserUrl struct {
	Id UserID `url:"id"`
}
// URL parameters for UpdateUser
type UpdateUserUrl struct {
	Id UserID `url:"id"`
}
// URL parameters for DeleteUser
type DeleteUserUrl struct {
	Id UserID `url:"id"`
}
// URL parameters for PatchUserProfile
type PatchUserProfileUrl struct {
	Id UserID `url:"id"`
}
// URL parameters for GetUsersByRole
type GetUsersByRoleUrl struct {
	Role UserRole `url:"role"`
}
// URL parameters for GetUserNotifications
type GetUserNotificationsUrl struct {
	UserId UserID `url:"userId"`
}

