// Package generated by API code generator
package server

import (
	"context"
	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/types"
	"github.com/medubin/gonzo/api/src/url"
)


type GonzoServer interface {
	// Authentication endpoints
	Signup(ctx context.Context, body *SignupRequest, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*SignupResponse, error)
	SignIn(ctx context.Context, body *SignInRequest, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*SignInResponse, error)
	SignOut(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*SignOutResponse, error)
	GetCurrentUser(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*GetUserResponse, error)
	// User management endpoints (require authentication)
	GetUser(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[struct{}, GetUserUrl]) (*GetUserResponse, error)
	GetUsers(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[GetUsersQuery, struct{}]) (*GetUsersResponse, error)
	UpdateUser(ctx context.Context, body *UpdateUserRequest, cookie cookies.Cookies, url url.URL[struct{}, UpdateUserUrl]) (*UpdateUserResponse, error)
}

func StartGonzoServer(s GonzoServer, r *router.Router) {
	r.Route(handle.Handle(s.Signup), &types.RouteInfo{
  Method: "POST",
  Path: "/auth/signup",
  Endpoint: "Signup",
  Server: "GonzoServer",
  RequiresBody: true,
  })
	r.Route(handle.Handle(s.SignIn), &types.RouteInfo{
  Method: "POST",
  Path: "/auth/signin",
  Endpoint: "SignIn",
  Server: "GonzoServer",
  RequiresBody: true,
  })
	r.Route(handle.Handle(s.SignOut), &types.RouteInfo{
  Method: "POST",
  Path: "/auth/signout",
  Endpoint: "SignOut",
  Server: "GonzoServer",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.GetCurrentUser), &types.RouteInfo{
  Method: "GET",
  Path: "/auth/me",
  Endpoint: "GetCurrentUser",
  Server: "GonzoServer",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.GetUser), &types.RouteInfo{
  Method: "GET",
  Path: "/user/{UserID}",
  Endpoint: "GetUser",
  Server: "GonzoServer",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.GetUsers), &types.RouteInfo{
  Method: "GET",
  Path: "/users",
  Endpoint: "GetUsers",
  Server: "GonzoServer",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.UpdateUser), &types.RouteInfo{
  Method: "PUT",
  Path: "/user/{UserID}",
  Endpoint: "UpdateUser",
  Server: "GonzoServer",
  RequiresBody: true,
  })
}

