// Package generated by API code generator
package server

import (
	"context"
	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/url"
)


type GonzoServer interface {
	Signup(ctx context.Context, body *SignupBody, cookie cookies.Cookies, url url.URL[struct{}]) (*SignupResponse, error)
	SignIn(ctx context.Context, body *SignInBody, cookie cookies.Cookies, url url.URL[struct{}]) (*SignInResponse, error)
	SignOut(ctx context.Context, body *SignOutBody, cookie cookies.Cookies, url url.URL[struct{}]) (*SignOutResponse, error)
	GetUser(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[GetUserUrl]) (*GetUserResponse, error)
	GetUsers(ctx context.Context, body *GetUsersBody, cookie cookies.Cookies, url url.URL[struct{}]) (*GetUsersResponse, error)
}

func StartGonzoServer(s GonzoServer, r *router.Router) {
	r.Route("POST", "/user/new", handle.Handle(s.Signup))
	r.Route("POST", "/session/new", handle.Handle(s.SignIn))
	r.Route("DELETE", "/session", handle.Handle(s.SignOut))
	r.Route("GET", "/user/{UserID}", handle.Handle(s.GetUser))
	r.Route("GET", "/users/", handle.Handle(s.GetUsers))
}

