// Package generated by API code generator
package server


type UserID int32

type User struct {
	ID *UserID `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type Session struct {
	UserID *UserID `json:"userid,omitempty"`
	Token *string `json:"token,omitempty"`
}

type SignupBody struct {
	User *User `json:"user,omitempty"`
	Password *string `json:"password,omitempty"`
}

type SignupResponse struct {
	User *User `json:"user,omitempty"`
}

type SignInBody struct {
	UserID *UserID `json:"userid,omitempty"`
	Password *string `json:"password,omitempty"`
}

type SignInResponse struct {
	Session *Session `json:"session,omitempty"`
}

type GetUserResponse struct {
	User *User `json:"user,omitempty"`
}

type GetUsersBody struct {
	UserIDs *[]UserID `json:"userids,omitempty"`
}

type GetUsersResponse struct {
	Users *map[UserID]User `json:"users,omitempty"`
}

type SignOutBody struct {
	Session *Session `json:"session,omitempty"`
}

type SignOutResponse struct {
}

type GetUserParams struct {
}

// URL parameters for GetUser
type GetUserUrl struct {
	UserID *UserID `url:"UserID"`
}
