// Code generated by Gonzo DO NOT EDIT.
package server

import (
	"context"

	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/url"
)

type UserID int32

type User struct {
	ID    *UserID
	Name  *string
	Email *string
}

type Session struct {
	UserID *UserID
	Token  *string
}

type SignupBody struct {
	User     *User
	Password *string
}

type SignupResponse struct {
	User *User
}

type SignInBody struct {
	UserID   *UserID
	Password *string
}

type SignInResponse struct {
	Session *Session
}

type GetUserResponse struct {
	User *User
}

type GetUsersBody struct {
	UserIDs []UserID
}

type GetUsersResponse struct {
	Users map[UserID]User
}

type SignOutBody struct {
	Session *Session
}

type SignOutResponse struct {
}

type SignupUrl struct {
}

type SignInUrl struct {
}

type SignOutUrl struct {
}

type GetUserUrl struct {
	UserID *string
}

type GetUsersUrl struct {
}

type GonzoServer interface {
	Signup(ctx context.Context, body *SignupBody, cookie cookies.Cookies, url url.URL[SignupUrl]) (*SignupResponse, error)
	SignIn(ctx context.Context, body *SignInBody, cookie cookies.Cookies, url url.URL[SignInUrl]) (*SignInResponse, error)
	SignOut(ctx context.Context, body *SignOutBody, cookie cookies.Cookies, url url.URL[SignOutUrl]) (*SignOutResponse, error)
	GetUser(ctx context.Context, body *interface{}, cookie cookies.Cookies, url url.URL[GetUserUrl]) (*GetUserResponse, error)
	GetUsers(ctx context.Context, body *GetUsersBody, cookie cookies.Cookies, url url.URL[GetUsersUrl]) (*GetUsersResponse, error)
}

func StartGonzoServer(s GonzoServer, r *router.Router) {
	r.Route("POST", "/user/new", handle.Handle(s.Signup))
	r.Route("POST", "/session/new", handle.Handle(s.SignIn))
	r.Route("DELETE", "/session", handle.Handle(s.SignOut))
	r.Route("GET", "/user/{UserID}", handle.Handle(s.GetUser))
	r.Route("GET", "/users/", handle.Handle(s.GetUsers))
}
