// Package generated by API code generator
package server

import (
	"fmt"
	"reflect"
)


type UserID int32

type User struct {
  ID *UserID `json:"id,omitempty"`
  Name *string `json:"name,omitempty"`
  Email *string `json:"email,omitempty"`
}

func (v User) Validate() error {
  return nil
}

type Session struct {
  UserID *UserID `json:"userid,omitempty"`
  Token *string `json:"token,omitempty"`
}

func (v Session) Validate() error {
  return nil
}

type SignupBody struct {
  User *User `json:"user,omitempty"`
  Password *string `json:"password,omitempty"`
}

func (v SignupBody) Validate() error {
  return nil
}

type SignupResponse struct {
  User *User `json:"user,omitempty"`
}

func (v SignupResponse) Validate() error {
  return nil
}

type SignInBody struct {
  UserID *UserID `json:"userid,omitempty"`
  Password *string `json:"password,omitempty"`
}

func (v SignInBody) Validate() error {
  return nil
}

type SignInResponse struct {
  Session *Session `json:"session,omitempty"`
}

func (v SignInResponse) Validate() error {
  return nil
}

type GetUserResponse struct {
  User *User `json:"user,omitempty"`
}

func (v GetUserResponse) Validate() error {
  return nil
}

type GetUsersBody struct {
  UserIDs *[]UserID `json:"userids,omitempty"`
}

func (v GetUsersBody) Validate() error {
  return nil
}

type GetUsersResponse struct {
  Users *map[UserID]User `json:"users,omitempty"`
}

func (v GetUsersResponse) Validate() error {
  return nil
}

type SignOutBody struct {
  Session *Session `json:"session,omitempty"`
}

func (v SignOutBody) Validate() error {
  return nil
}

type SignOutResponse struct {
}

func (v SignOutResponse) Validate() error {
  return nil
}

type GetUserParams struct {
}

func (v GetUserParams) Validate() error {
  return nil
}

// URL parameters for GetUser
type GetUserUrl struct {
	UserID *UserID `url:"UserID"`
}
