// Package generated by API code generator
package user_service

/*
 * Servers contain endpoints.
 * Each endpoint is defined as a name, verb url, optional body and optional returns
 */
type UserServiceImpl struct {
	// Add your server implementation fields here
}
