package simplegolangserverparser

import (
	"go/format"

	lex "github.com/medubin/gonzo/api/generate/lexer"
)

type Parser struct {
	lexer lex.Lexer
}

type ParseOptions struct {
	SkipServer bool
}

func NewParser(lexer lex.Lexer) Parser {
	return Parser{
		lexer: lexer,
	}
}

func (p *Parser) Parse(options ParseOptions) (string, map[string]string, error) {
	text := `// Code generated by Gonzo DO NOT EDIT.
package server
`
	if !options.SkipServer {
		text += `
import (
	"context"

	"github.com/medubin/gonzo/api/src/cookies"
	"github.com/medubin/gonzo/api/src/handle"
	"github.com/medubin/gonzo/api/src/router"
	"github.com/medubin/gonzo/api/src/url"
)
	
	`
	}
	fieldStarted := false
	server := server{}

	for !p.lexer.IsEOF() {
		token := p.lexer.Next()
		switch token.State {
		case lex.STATE_SERVER:
			if !options.SkipServer {
				server.ParseServer(token)
			}
		case lex.STATE_BODY:
			server.ParseBody(token)
		case lex.STATE_RETURNS:
			server.ParseReturns(token)
		case lex.STATE_NONE:
			// we can add filtering here for illegal top levels tokens
			text += token.Chars
		case lex.STATE_REPEATED:
			switch token.Type {
			case lex.LP:
				text += "[]"
			case lex.RP:
			case lex.REPEATED:
				// do nothing
			default:
				text += token.Chars
			}
		case lex.STATE_MAP:
			switch token.Type {
			case lex.LP:
				text += "["
			case lex.COLON:
				text += "]"
			case lex.RP:
			case lex.SPACE:
				// do nothing
			default:
				text += token.Chars
			}
		case lex.STATE_TYPE:
			switch token.Type {
			default:
				text += token.Chars
			}
		case lex.STATE_FIELD:
			switch token.Type {
			case lex.LCB:
				text += " struct {"
			case lex.IDENT:
				if !fieldStarted {
					fieldStarted = true
				} else {
					text += "*"
				}
				text += token.Chars
			case lex.NEWLINE:
				fieldStarted = false
				text += token.Chars
			default:
				text += token.Chars
			}
		}
	}
	if !options.SkipServer {
		text += server.OutputTypes()
	}

	formattedOutput, err := format.Source([]byte(text))
	if err != nil {
		return "", nil, err
	}
	var endpoints map[string]string
	if !options.SkipServer {
		endpoints = server.OutputEndpoints()
	}

	return string(formattedOutput), endpoints, nil
}
