// Package generated by API code generator
package media_service

import (
	"context"
	server "github.com/medubin/gonzo/code_generator/generator/test_data/server"
	"github.com/medubin/gonzo/runtime/cookies"
	"github.com/medubin/gonzo/runtime/handle"
	"github.com/medubin/gonzo/runtime/router"
	"github.com/medubin/gonzo/runtime/types"
	"github.com/medubin/gonzo/runtime/url"
)

type MediaService interface {
	UploadAvatar(ctx context.Context, body *server.UploadAvatarRequest, cookie cookies.Cookies, url url.URL[struct{}, server.UploadAvatarUrl]) (*handle.Response[server.UploadResult], error)
}

func StartMediaService(s MediaService, r *router.Router) error {
	if err := r.Route(handle.HandleMultipart(s.UploadAvatar), &types.RouteInfo{
		Method:       "POST",
		Path:         "/users/{id}/avatar",
		Endpoint:     "UploadAvatar",
		Server:       "MediaService",
		RequiresBody: true,
		IsMultipart:  true,
	}); err != nil {
		return err
	}
	return nil
}
