// Generated by API code generator


// enums can be defined like this
// enums can be any primitive type
export type UserRole = "admin" | "moderator" | "user";

export type UserStatus = "active" | "pending" | "suspended";

export type WelcomeMessage = "Welcome to \"MyApp\"";

export type UserSomething = 0 | 2 | 1;



// this is a comment
/* this is a multiline comment */
// you can define primitives like this
export type UserID = number;


// this is also a comment
export type Email = string;


export type Timestamp = number;


export type Score = number;


export type IsActive = boolean;


// you can defined lists this way
export type UserList = Array<User>;


// you can use types before they are defined
export type NotificationID = number;


// lists can be complex
export type UserRoleHistory = Array<Array<string>>;


export type NestedUserGroups = Array<Array<UserList>>;


// you can defined maps this way
export type UserPermissions = Record<string, boolean>;


// maps can be complex
export type UserActivityByMonth = Record<string, Record<number, Array<number>>>;


// structs can be defined like this
export interface User {
  id?: UserID;
  username?: string;
  email?: Email;
  role?: UserRole;
}


/*
 * Struct fields can contain:
 * ** any primitives
 * ** repeated fields
 * ** map fields
 * ** any defined types
 * ** other structs
 */
export interface DetailedUser {
	// fields are optional unless marked with 'required'
  id: UserID;
  usernames?: Array<string>;
  loginCount?: Record<string, number>;
  profile?: UserProfile;
}


export interface UserProfile {
  firstName?: string;
  lastName?: string;
  bio?: string;
  avatarUrl?: string;
}


// both lists and maps can contain structs
export type UserCollection = Array<User>;


export type UsersByDepartment = Record<string, User>;


/*
 * Allowed in parameter structs:
 * - Primitives: string, int32, int64, float32, float64, bool
 * - Enums (serialize to underlying primitive)
 * - Simple arrays: repeated(primitive) or repeated(enum)
 * - Maybe simple maps: map(string: primitive)
 */
export interface UserSearchParams {
  query?: string;
  roles?: Array<UserRole>;
  isActive?: boolean;
  limit?: number;
}


export interface UserListParams {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: string;
}


export interface CreateUserRequest {
  username: string;
  email: Email;
  password: string;
  role?: UserRole;
  profile?: UserProfile;
}


export interface UpdateUserRequest {
  username?: string;
  email?: Email;
  role?: UserRole;
  status?: UserStatus;
}


export interface DeleteUserRequest {
  reason?: string;
  transferDataTo?: UserID;
}


export interface UserProfileUpdate {
  firstName?: string;
  lastName?: string;
  bio?: string;
  avatarUrl?: string;
}


export interface Notification {
  id?: NotificationID;
  title?: string;
  message?: string;
  createdAt?: Timestamp;
  isRead?: boolean;
}



export interface GetUserParams {
  id: UserID;
}
export interface UpdateUserParams {
  id: UserID;
}
export interface DeleteUserParams {
  id: UserID;
}
export interface PatchUserProfileParams {
  id: UserID;
}
export interface GetUsersByRoleParams {
  role: UserRole;
}
export interface GetUserNotificationsParams {
  userId: UserID;
}

