// Package generated by API code generator
package server

import (
	"net/http"

	"github.com/medubin/gonzo/runtime/cookies"
)

// Cookie name constants — use these instead of string literals so a typo
// is a compile error and the set of declared cookies is discoverable.
const (
	SessionCookieName = "session"
	LocaleCookieName  = "locale"
)

// SetSession sets the session cookie. The security attributes
// declared via @cookie in the .api file are baked in; opts can extend
// (e.g., MaxAge, Path) but cannot disable a declared attribute.
func SetSession(c cookies.Cookies, value string, opts ...cookies.Opt) {
	cookie := &http.Cookie{
		Name:     SessionCookieName,
		Value:    value,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
	}
	for _, opt := range opts {
		opt(cookie)
	}
	c.Set(cookie)
}
