// Package generated by API code generator
package server

import (
	"context"
	"github.com/medubin/gonzo/runtime/cookies"
	"github.com/medubin/gonzo/runtime/handle"
	"github.com/medubin/gonzo/runtime/router"
	"github.com/medubin/gonzo/runtime/types"
	"github.com/medubin/gonzo/runtime/url"
)

/*
 * Servers contain endpoints.
 * Each endpoint is defined as a name, verb url, optional body and optional returns
 */
type UserService interface {
	// Endpoints can contain url parameters, which can be any primitive type or enum
	// GET endpoints do not contain a body
	GetUser(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[struct{}, GetUserUrl]) (*handle.Response[DetailedUser], error)
	// All other urls can contain a body
	// body and return always refer to a struct type
	CreateUser(ctx context.Context, body *CreateUserRequest, cookie cookies.Cookies, url url.URL[struct{}, struct{}]) (*handle.Response[User], error)
	UpdateUser(ctx context.Context, body *UpdateUserRequest, cookie cookies.Cookies, url url.URL[struct{}, UpdateUserUrl]) (*handle.Response[User], error)
	DeleteUser(ctx context.Context, body *DeleteUserRequest, cookie cookies.Cookies, url url.URL[struct{}, DeleteUserUrl]) (*handle.Response[User], error)
	PatchUserProfile(ctx context.Context, body *UserProfileUpdate, cookie cookies.Cookies, url url.URL[struct{}, PatchUserProfileUrl]) (*handle.Response[UserProfile], error)
	// Endpoints can take a struct of parameters
	ListUsers(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, struct{}]) (*handle.Response[UserCollection], error)
	SearchUsers(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserSearchParams, struct{}]) (*handle.Response[UserCollection], error)
	GetUsersByRole(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, GetUsersByRoleUrl]) (*handle.Response[UserCollection], error)
}

func StartUserService(s UserService, r *router.Router) {
	r.Route(handle.Handle(s.GetUser), &types.RouteInfo{
  Method: "GET",
  Path: "/users/{id}",
  Endpoint: "GetUser",
  Server: "UserService",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.CreateUser), &types.RouteInfo{
  Method: "POST",
  Path: "/users",
  Endpoint: "CreateUser",
  Server: "UserService",
  RequiresBody: true,
  })
	r.Route(handle.Handle(s.UpdateUser), &types.RouteInfo{
  Method: "PUT",
  Path: "/users/{id}",
  Endpoint: "UpdateUser",
  Server: "UserService",
  RequiresBody: true,
  })
	r.Route(handle.Handle(s.DeleteUser), &types.RouteInfo{
  Method: "DELETE",
  Path: "/users/{id}",
  Endpoint: "DeleteUser",
  Server: "UserService",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.PatchUserProfile), &types.RouteInfo{
  Method: "PATCH",
  Path: "/users/{id}/profile",
  Endpoint: "PatchUserProfile",
  Server: "UserService",
  RequiresBody: true,
  })
	r.Route(handle.Handle(s.ListUsers), &types.RouteInfo{
  Method: "GET",
  Path: "/users",
  Endpoint: "ListUsers",
  Server: "UserService",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.SearchUsers), &types.RouteInfo{
  Method: "GET",
  Path: "/users/search",
  Endpoint: "SearchUsers",
  Server: "UserService",
  RequiresBody: false,
  })
	r.Route(handle.Handle(s.GetUsersByRole), &types.RouteInfo{
  Method: "GET",
  Path: "/users/role/{role}",
  Endpoint: "GetUsersByRole",
  Server: "UserService",
  RequiresBody: false,
  })
}

// multiple servers can be defined in a single file
type NotificationService interface {
	GetUserNotifications(ctx context.Context, body *struct{}, cookie cookies.Cookies, url url.URL[UserListParams, GetUserNotificationsUrl]) (*handle.Response[[]Notification], error)
}

func StartNotificationService(s NotificationService, r *router.Router) {
	r.Route(handle.Handle(s.GetUserNotifications), &types.RouteInfo{
  Method: "GET",
  Path: "/users/{userId}/notifications",
  Endpoint: "GetUserNotifications",
  Server: "NotificationService",
  RequiresBody: false,
  })
}

