// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package queries

import (
	"time"
)

type Session struct {
	ID        int32
	UserID    int32
	Token     string
	CreatedAt time.Time
}

type User struct {
	ID        int32
	Username  string
	Password  string
	Email     string
	CreatedAt time.Time
}
