// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: session.sql

package queries

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id, token
) VALUES (
  $1, $2
)
RETURNING id, user_id, token, created_at
`

type CreateSessionParams struct {
	UserID int32
	Token  string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.Token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}
