// Package generated by API code generator
package notification_service

// multiple servers can be defined in a single file
type NotificationServiceImpl struct {
	// Add your server implementation fields here
}
